version: 2
jobs:
  build:
    machine:
      pre:
        - sudo apt-get update && sudo apt-get install -y texlive-full
          #        - sudo apt-get install texlive-latex-base
    steps:
      - checkout

      - run:
          name: "Install Deps"
          command: |
                sudo apt-get update -yqq
                sudo apt-get install -y texlive-full
                sudo apt-get -y install biber
                sudo apt-get install poppler-utils

      - run:
          name: "Update Submodule"
          command: |
              git submodule init
              git submodule update --remote 
      - run:
          name: "Remove old files"
          command: rm -f thesis/thesis.*
      - run: 
          name: "First PDFLaTeX"
          command: pdflatex  -output-directory=thesis/  thesis.tex

      - run:
          name: "Run biber (not justin)"
          command: |
              cd thesis
              biber thesis
              cd ../

      - run:
          name: "Second PDFLaTeX"
          command: pdflatex  -output-directory=thesis/  thesis.tex

      - run:
          name: "Third PDFLaTeX"
          command: pdflatex  -output-directory=thesis/  thesis.tex

      - run:
          name: "Check if output exists"
          command: ls thesis/thesis.pdf

      - run:
          name: "Check if '??' references exist"
          command: |
              export ALL_REFS_OK=$( pdftotext thesis/thesis.pdf - |grep "??" )
              [[ ! -z "$ALL_REFS_OK" ]] && { echo "There are undefined references\n" ; echo $ALL_REFS_OK ; exit 1; }
