version: 2
jobs:
  build:
    machine:
      pre:
        - sudo apt-get install texlive-xetex
        - sudo apt-get install texlive-latex-base
    steps:
      - checkout

      - run:
          name: "Update Submodule"
          command: |
              git submodule init
              git submodule update --remote 
      - run:
          name: "Remove old files"
          command: rm -f thesis/thesis.*
      - run: 
          name: "First PDFLaTeX"
          command: pdflatex  -output-directory=thesis/  thesis.tex
