version: 2
jobs:
  build:
    machine:
      pre:
        - sudo apt-get update && sudo apt-get install -y texlive-full
          #        - sudo apt-get install texlive-latex-base
    steps:
      - checkout

      - run:
          name: "Install Deps"
          command: |
                sudo apt-get update -yqq
                sudo apt-get install -y texlive-full
      - run:
          name: "Update Submodule"
          command: |
              git submodule init
              git submodule update --remote 
      - run:
          name: "Remove old files"
          command: rm -f thesis/thesis.*
      - run: 
          name: "First PDFLaTeX"
          command: pdflatex  -output-directory=thesis/  thesis.tex

      - run:
          name: "Run biber (not justin)"
          command: |
              cd thesis
              biber thesis
              cd ../

      - run:
          name: "Second PDFLaTeX"
          command: pdflatex  -output-directory=thesis/  thesis.tex

      - run:
          name: "Third PDFLaTeX"
          command: pdflatex  -output-directory=thesis/  thesis.tex

      -run:
          name: "Check if output exists"
          command: ls thesis/thesis.pdf
