version: 2
jobs:
  build:
    docker:
      image: apmechev/thesisbuilder:v0.1
    steps:
      - checkout

      - run:
          name: "Update Submodule"
          command: |
              git submodule init
              git submodule update --remote 
      - run:
          name: "Remove old files"
          command: rm -f thesis/thesis.*
      - run: 
          name: "First PDFLaTeX"
          command: pdflatex  -output-directory=thesis/  thesis.tex

      - run:
          name: "Run biber (not justin)"
          command: |
              cd thesis
              biber thesis
              cd ../

      - run:
          name: "Second PDFLaTeX"
          command: pdflatex  -output-directory=thesis/  thesis.tex

      - run:
          name: "Third PDFLaTeX"
          command: pdflatex  -output-directory=thesis/  thesis.tex

      - run:
          name: "Check if output exists"
          command: ls thesis/thesis.pdf

      - run:
          name: "Check if '??' references exist"
          command: |
              export ALL_REFS_OK=$( pdftotext thesis/thesis.pdf - |grep "??" )
              [[ ! -z "$ALL_REFS_OK" ]] && { echo "There are undefined references\n" ; echo $ALL_REFS_OK ; exit 1; } || exit 0; 
